version: 2

builds:
  - main: ./main.go
    binary: "{{ .Os }}-{{ .Arch }}"
    no_unique_dist_dir: true
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .Binary }}"

release:
  draft: false
  prerelease: auto
